version: "3.5"

services:
  # Global Dashboard
  heimdall:
    image: linuxserver/heimdall
    container_name: cinema-heimdall
    ports:
      - 801:80
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/bgalhardo/Phoenix/configs/heimdall:/config
    networks:
      - cinema-network
      - hal-network
    restart: always

  transmission:
    container_name: cinema-transmission
    image: linuxserver/transmission
    restart: unless-stopped
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
      - USER=admin
      - PASS=admin
    volumes: 
      - /media/bgalhardo/Phoenix/configs/transmission:/config 
      - downloads-complete:/downloads 
      - /media/bgalhardo/Phoenix/Downloads/incomplete:/var/lib/transmission-daemon/incomplete
    ports:
      - 9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - cinema-network

  plex:
    container_name: cinema-plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Lisbon
      - PLEX_CLAIM=
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ADVERTISE_IP="http://192.168.8.101:32400/"
      - ALLOWED_NETWORKS="192.168.8.0/24"
    volumes:
      - /media/bgalhardo/Phoenix/configs/plex:/config
      - /opt/transcode:/transcode
      - Phoenix-plex:/data/Phoenix
      - Leviathan-movies:/data/Leviathan/Movies
      - Leviathan-series:/data/Leviathan/Series
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900
      - 1900:1900/udp
      - 32410:32410
      - 32410:32410/udp
      - 32412:32412
      - 32412:32412/udp
      - 32413:32413
      - 32413:32413/udp
      - 32414:32414
      - 32414:32414/udp

  sonarr:
    container_name: cinema-sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/bgalhardo/Phoenix/configs/sonarr:/config
      - Leviathan-series:/tv
      - Phoenix-plex:/Phoenix-media
      - downloads-complete:/downloads
    ports:
      - 8989
    networks:
      - cinema-network

  radarr:
    container_name: cinema-radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - transmission
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/bgalhardo/Phoenix/configs/radarr:/config
      - Phoenix-plex:/Phoenix-media
      - Leviathan-movies:/movies
      - downloads-complete:/downloads
    ports:
      - 7878
    networks:
      - cinema-network

  jackett:
    image: linuxserver/jackett
    container_name: cinema-jackett
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
#      - RUN_OPTS=run options here #optional
    volumes:
      - /media/bgalhardo/Phoenix/configs/jackett:/config
      - downloads-complete:/downloads
    ports:
      - 9117
    networks:
      - cinema-network
    restart: unless-stopped

  grafana:
    # Dashboard UI
    image: grafana/grafana
    container_name: hal-grafana
    environment:
      - GF_INSTALL_PLUGINS=andig-darksky-datasource
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_CONFIG=/var/lib/grafana/custom.ini
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/grafana-config:/var/lib/grafana
    networks:
      - hal-network

  prometheus:
    # Database
    image: prom/prometheus:latest
    container_name: hal-prometheus
    ports:
      - 9090
    command:
      - --config.file=/prometheus/prometheus.yml
      - --storage.tsdb.retention.size=700GB
    restart: always
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/prometheus-db:/prometheus
    networks:
      - hal-network

  smart_plug_conn:
    # broadcast smart plug measurements
    build: ./HS110-interface
    container_name: hal-HS110
    ports:
      - 9999
    restart: always
    networks:
      - hal-network

  device_discovery:
    # discovering plugs for now
    # TODO add here the delay between broadcasts
    build: ./device_discovery
    container_name: hal-discovery
    network_mode: host
    restart: always

  cadvisor:
    # container monitoring
    image: gcr.io/google-containers/cadvisor:latest
    container_name: hal-cadvisor
    ports:
      - 8080
    command:
      - '--housekeeping_interval=10s'
      - '--disable_metrics=diskIO,tcp,udp,percpu,sched,process'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hal-network

  redis:
    # cache values
    image: redis:rc-alpine
    container_name: hal-redis
    ports:
      - 6380:6379
    restart: 'always'
    networks:
      - hal-network

  #ipcam-control:
  #  # TODO add cam password as env
  #  # sends commands to ipcam
  #  build: ipcam-control
  #  container_name: hal-ipcam-control
  #  restart: always
  #  networks:
  #    - hal-network
  #   records ipcam feed
  #ipcam-record:
  #  build: ./ipcam-record
  #  container_name: automation-ipcam-record
  #  restart: always
  #  volumes:
  #    - /media/bgalhardo/Bahamut/home-automation/ipcam-videos:/videos/
  #restreamer:
  #  container_name: automation-restreamer
  #  image: datarhei/restreamer:latest
  #  environment:
  #    - RS_LOGLEVEL=4
  #  ports:
  #    - 3001:8080
  #   volumes:
  #     - /mnt/restreamer/db:/restreamer/db

volumes:
  downloads-complete:
    driver: local
    driver_opts:
      type: none
      device: /media/bgalhardo/Phoenix/Downloads/complete
      o: bind
  Phoenix-plex:
    driver: local
    driver_opts:
      type: none
      device: /media/bgalhardo/Phoenix/plex-server
      o: bind
  Leviathan-movies:
    driver: local
    driver_opts:
      type: none
      device: /media/bgalhardo/Leviathan/plex-server/Movies
      o: bind
  Leviathan-series:
    driver: local
    driver_opts:
      type: none
      device: /media/bgalhardo/Leviathan/plex-server/Series
      o: bind

networks:
  cinema-network:
    name: cinema-network
    driver: bridge
  hal-network:
    name: hal-network 
    driver: bridge
