version: "3.5"

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

services:
  grafana:
    # Dashboard UI
    <<: *logging
    image: grafana/grafana
    container_name: hal-grafana
    environment:
      - GF_INSTALL_PLUGINS=andig-darksky-datasource,agenty-flowcharting-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_CONFIG=/var/lib/grafana/custom.ini
    ports:
      - 3000:3000
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/grafana-config:/var/lib/grafana
    restart: always
    networks:
      - hal-network

  prometheus:
    # Database
    <<: *logging
    image: prom/prometheus:latest
    container_name: hal-prometheus
    command:
      - --config.file=/prometheus/prometheus.yml
      - --storage.tsdb.retention.size=700GB
#      - --web.enable-admin-api
    ports:
      - 9090
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/prometheus-db:/prometheus
    restart: always
    networks:
      - hal-network

  smart_plug_conn:
    # broadcast smart plug measurements
    <<: *logging
    build: ./HS110-interface
    container_name: hal-HS110
    environment:
      - DISCOVERY_PERIOD=60
      - UPDATE_PERIOD=5
    ports:
      - 9999
    restart: always
    networks:
      - hal-network

  device_discovery:
    # discovering plugs for now
    # TODO add here the delay between broadcasts
    <<: *logging
    build: ./device_discovery
    container_name: hal-discovery
    environment:
      - DISCOVERY_PERIOD=30
    restart: always
    network_mode: host

  cadvisor:
    # container monitoring
    <<: *logging
    image: gcr.io/google-containers/cadvisor:latest
    container_name: hal-cadvisor
    command:
      - '--housekeeping_interval=10s'
      - '--disable_metrics=diskIO,tcp,udp,percpu,sched,process'
    ports:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hal-network

  redis:
    # cache values
    <<: *logging
    image: redis:rc-alpine
    container_name: hal-redis
    ports:
      - 6380:6379
    restart: 'always'
    networks:
      - hal-network

  loki:
    <<: *logging
    image: grafana/loki:master
    container_name: hal-loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
#    volumes:
#      - ./loki/config.yml:/etc/loki/config.yaml
#      - /data/volumes/loki:/data/loki
    networks:
      - hal-network

#  promtail:
#    image: grafana/promtail:master
#    container_name: hal-promtail
#    volumes:
#      - /var/log:/var/log
#      - /media/bgalhardo/Bahamut/home-automation/promtail-db:/promtail
#    command: -config.file=/promtail/config.yaml
#    networks:
#      - hal-network

  #ipcam-control:
  #  # TODO add cam password as env
  #  # sends commands to ipcam
  #  build: ipcam-control
  #  container_name: hal-ipcam-control
  #  restart: always
  #  networks:
  #    - hal-network
  #   records ipcam feed
  #ipcam-record:
  #  build: ./ipcam-record
  #  container_name: automation-ipcam-record
  #  restart: always
  #  volumes:
  #    - /media/bgalhardo/Bahamut/home-automation/ipcam-videos:/videos/


networks:
  hal-network:
    name: hal-network