version: "3.5"

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"

services:
  grafana:
    # Dashboard UI
    <<: *logging
    image: grafana/grafana
    container_name: hal-grafana
    environment:
      - GF_INSTALL_PLUGINS=andig-darksky-datasource,agenty-flowcharting-panel,grafana-clock-panel,natel-discrete-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_PATHS_CONFIG=/var/lib/grafana/custom.ini
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    ports:
      - 3000:3000
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/grafana-config:/var/lib/grafana
    restart: always
    networks:
      - hal-network

  grafana-renderer:
    <<: *logging
    image: grafana/grafana-image-renderer:latest
    container_name: hal-grafana-renderer
    restart: always
    ports:
      - 8081
    networks:
      - hal-network

  prometheus:
    # Database
    <<: *logging
    image: prom/prometheus:latest
    container_name: hal-prometheus
    command:
      - --config.file=/prometheus/prometheus.yml
      - --storage.tsdb.retention.size=700GB
#      - --web.enable-admin-api
    ports:
      - 9090
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/prometheus-db:/prometheus
    restart: always
    networks:
      - hal-network

  prometheus-metrics:
    # broadcast smart plug measurements
    <<: *logging
    build: ./prometheus-metrics
    container_name: hal-prometheus-metrics
    environment:
      - DISCOVERY_PERIOD=30
      - UPDATE_PERIOD=5
      - SERVER_PORT=9999
      - EDP_CONTROLLER=http://edp:5000
      - BULB_CONTROLLER=http://192.168.8.101:5001
      - PLUG_CONTROLLER=http://192.168.8.101:5002
    restart: always
    ports:
      - 9999
    networks:
      - hal-network

  speedtest:
    # endpoint for internet speed tests
    <<: *logging
    image: jraviles/prometheus_speedtest:latest
    container_name: hal-speedtest
    restart: always
    ports:
      - 9516:9516
    networks:
      - hal-network

  cadvisor:
    # container monitoring
    <<: *logging
    image: gcr.io/google-containers/cadvisor:latest
    container_name: hal-cadvisor
    command:
      - '--housekeeping_interval=10s'
      - '--disable_metrics=diskIO,tcp,udp,percpu,sched,process'
    ports:
      - 8080
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - hal-network

  consul:
    # log sensor ips
    <<: *logging
    image: consul:latest
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -node=HAL9000"
    container_name: hal-consul
    restart: always
    volumes:
      - /media/bgalhardo/Bahamut/home-automation/consul:/consul/data
    ports:
      - 8500:8500
    networks:
      - hal-network

  consul-esm:
    # allows health check to consul external services
    <<: *logging
    build: consul-esm
    restart: always
    container_name: hal-consul-esm
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - hal-network

  loki:
    # logger
    <<: *logging
    image: grafana/loki:master
    container_name: hal-loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
#    volumes:
#      - ./loki/config.yml:/etc/loki/config.yaml
#      - /data/volumes/loki:/data/loki
    restart: always
    networks:
      - hal-network

  restreamer:
    # to convert rtsp -> html
    <<: *logging
    image: datarhei/restreamer:latest
    container_name: hal-restreamer
    environment:
      - RS_INPUTSTREAM=rtsp://admin:notoo7luke@192.168.8.99:10554/tcp/av0_0
      - RS_USERNAME=admin
      - RS_PASSWORD=admin
    restart: always
    ports:
      - 8080:8080
    networks:
      - hal-network

  redis:
    image: redis:rc-alpine
    container_name: hal-redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - hal-network

  edp:
    # smart meter api
    <<: *logging
    build: ./edp
    container_name: hal-edp
    environment:
      - USERNAME
      - PASSWORD
      - ADDRESS=https://online.e-redes.pt/listeners/api.php/ms
      - PORT=5000
    restart: always
    ports:
      - 5000
    networks:
      - hal-network

  lifx:
    # lifx bulbs api
    <<: *logging
    build: ./lifx
    container_name: hal-lifx
    environment:
      - MODULE_NAME=lifx
      - PORT=5001
    restart: always
    network_mode: host

  smartplug:
    # kasa plugs api
    <<: *logging
    build: ./smartplug
    container_name: hal-smartplug
    environment:
      - BROADCAST_IP=192.168.8.255
      - MODULE_NAME=smartplug
      - PORT=5002
    restart: always
    network_mode: host

  #ipcam-control:
  #  # TODO add cam password as env
  #  # sends commands to ipcam
  #  build: ipcam-control
  #  container_name: hal-ipcam-control
  #  restart: always
  #  networks:
  #    - hal-network
  #   records ipcam feed
  #ipcam-record:
  #  build: ./ipcam-record
  #  container_name: automation-ipcam-record
  #  restart: always
  #  volumes:
  #    - /media/bgalhardo/Bahamut/home-automation/ipcam-videos:/videos/


networks:
  hal-network:
    name: hal-network
